<a href="https://colab.research.google.com/github/SadmanAdib13/First-Project/blob/main/numpy(cse110).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Task 1
import numpy as np
n=int(input("Enter a number:"))
array=np.zeros(n,dtype=int)
print(array)

for i in range(n):
  array[i]=int(input("Enter a number for the array:"))
print ("Original Array :",array)

new_array=np.zeros(n+1,dtype=int)

for j in range(n):
  new_array[j]=array[j]

m=int(input("Enter a new number:"))
new_array[n]=m

print("Resized Array:",new_array)


Enter a number:3
[0 0 0]
Enter a number for the array:5
Enter a number for the array:6
Enter a number for the array:2
Original Array : [5 6 2]
Enter a new number:9
Resized Array: [5 6 2 9]


In [ ]:
#Task 2
n=int(input("Enter array size :"))
array=np.zeros(n,dtype=int)
for i in range(n):
  array[i]=int(input())

print("Original array :",array)

new_array=np.zeros(n,dtype=int)
for i in range(n):
  if array[i]==0 or array[i]<0:
    new_array[i]=0

  else :
    new_array[i]=1

print("After modifying :",new_array)


Enter array size :5
4
3
4
-2
1
Original array : [ 4  3  4 -2  1]
After modifying : [1 1 1 0 1]


In [ ]:
#Task 3
import numpy as np
def reverseArray(n):


  i=0
  j=n.size-1

  while i<j:
    n[i],n[j]=n[j],n[i]
    i=+1
    j=-1
  return n


arr1=np.array([10,12,20,5,7])
arr1=reverseArray(arr1)
print(arr1)

[ 7 12 20  5 10]


In [ ]:
#Task 4
def printParis(array,result):
  flag=False
  for i in range (array.size):
    for j in range(i+1,array.size):
      if array[i]+array[j]==result:
        flag=True
        print(array[i],array[j])
  if flag==False:
    print("No pair found.")

arr1=np.array([7,8,10,5,3,4,2])
printParis(arr1,15)

7 8
10 5


In [ ]:
#Task 5
vec1=np.array([1,2,3])
vec2=np.array([4,5,6])
dot_prod=0

for i in range(vec1.size):
  dot_prod=dot_prod+vec1[i]*vec2[i]
print("Dot Product :",dot_prod)
if dot_prod%2==0:
  for j in range(vec1.size):
    if j%2==0:
      vec1[j],vec2[j]=vec2[j],vec1[j]

else:
  for j in range(vec1.size):
    if j%2!=0:
      vec1[j],vec2[j]=vec2[j],vec1[j]

print("After Swaping:")
print(vec1)
print(vec2)

Dot Product : 32
After Swaping:
[4 2 6]
[1 5 3]


In [ ]:
#task6
import numpy as np

n = int(input("Enter the size of the array: "))
array = np.zeros(n, dtype=int)

for i in range(n):
    array[i] = int(input("Enter a number: "))
print("Original Array:", array)

for i in range(n-1):
    temp = i
    for j in range(i+1, n):
        if array[j] < array[temp]:
            temp = j
    if i != temp:
        array[i], array[temp] = array[temp], array[i]

print("Sorted Array:", array)

Enter the size of the array: 6
Enter a number: 6
Enter a number: 3
Enter a number: 1
Enter a number: 2
Enter a number: 8
Enter a number: 5
Original Array: [6 3 1 2 8 5]
Sorted Array: [1 2 3 5 6 8]


In [ ]:
#Task 7
def flatten(array):

  row=array.shape[0]
  col=array.shape[1]
  new_array=np.zeros(array.size,dtype=int)


  index=0
  for i in range(row):
    for j in range(col):
      new_array[index]=array[i][j]
      index=index+1
  return new_array

arr1=np.array([[1,2,3],[3,4,5]])
arr2=flatten(arr1)
print(arr2)

[1 2 3 3 4 5]


In [ ]:
#Task 8
import numpy as np
A = np.array([  [1,  0,  0,  1],
                [0,  1,  0,  0],
                [1,  0,  1,  0],
                [0,  1,  0,  1] ])

n = A.shape[0]
flag = True

for i in range(n):
    for j in range(n):
        if (i == j) and (A[i][j] != 1):
           flag = False
        elif (i != j) and (A[i][j] != 0):
           flag = False

if flag==True :
    print("Identity matrix")
else:
    print("Not an Identiy matrix")

Not an Identiy matrix


In [ ]:
#Task 9
import numpy as np

A = np.array([  [1,   5,  12,   1],
                [2,  -4,  6,    7],
                [3,   8,  5,    9],
                [3,   5,  23,  -6] ])

n = A.shape[0]

temp1 = 0
temp2 = 0

for i in range(n):
    for j in range(n):
        if i == j:
            temp1 += A[i][j]
        if i + j == n - 1:
            temp2 += A[i][j]
print(abs(temp1 - temp2))

22


In [ ]:
#Task 10.1
A = np.array(  [[1,2,3,4],
                [1,4,9,16]])

row = A.shape[0]
col = A.shape[1]
array = np.zeros(shape=(col,row), dtype=int)

for i in range(col):
    for j in range(row):
        array[i][j] = A[j][i]

print(array)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [ ]:
#Task 10.2
import numpy as np
A = np.array(  [[1, 2, 3, 4 ],
                [1, 4, 9, 16]])

row = A.shape[0]
col = A.shape[1]

array1 = np.zeros(shape=(col,row), dtype=int)

for i in range(col):
    for j in range(row):
        array1[i][j] = A[j][i]

array2 = np.zeros(shape=(col,col), dtype=int)

for i in range(col):
    for j in range(col):
        trans= array1[i]
        cis = A[:, j]
        sum = 0
        for k in range(len(trans)):
            sum += trans[k] * cis[k]
        array2[i][j] = sum
print(array2)

[[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]


In [ ]:
#Task 11
A = np.array([ [4,1,2],
               [9,3,7]])
array = np.zeros(shape=A.shape)
row = A.shape[0]
col = A.shape[1]
absDiff = abs(row-col)
rem = absDiff % row
new_Row = A[rem]
size = new_Row.size
sum = 0

for i in new_Row:
    sum += i
avg = round(sum/size, 2)


for i in range(M):
    for j in range(N):
        array[i][j] = avg * A[i][j]
print(array)

[[25.32  6.33 12.66]
 [56.97 18.99 44.31]]


In [ ]:
def one_call(n):
    print("In One call")
    if n % 3 == 0:
     return n + 7
     print("one Call Done")
    return n - 9

def two_call(a, b=20, c="sayounara"):
    a += b // 2 + 6
    if type(c) == str:
        b = c[b] + c[len(c) - b]
    else:
        b = (b + c) % 3
    result = one_call(a)
    print(result)
    if type(b) == str:
        return b, c


x, y = two_call(11, 3)
t = two_call(3, 8, 12)
print(t)
print(x, y)

In One call
25
In One call
4
None
oa sayounara
